"""empty message

Revision ID: 487c1b00cdbf
Revises: c043712a0a7e
Create Date: 2024-12-01 22:06:02.376927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487c1b00cdbf'
down_revision = 'c043712a0a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
