"""empty message

Revision ID: c043712a0a7e
Revises: 2a29e2c95ec6
Create Date: 2024-11-29 14:05:29.575737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c043712a0a7e'
down_revision = '2a29e2c95ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cliente', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_cocina', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('is_cocina')
        batch_op.drop_column('is_cliente')

    # ### end Alembic commands ###
