"""empty message

Revision ID: d358d4782905
Revises: 50b0a4236465
Create Date: 2024-12-10 17:49:02.282472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd358d4782905'
down_revision = '50b0a4236465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserve', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserve', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
